# Generated by Django 5.0.6 on 2024-05-19 18:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_add_user_id_to_phonebook'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callrecords',
            name='call_timestamp',
            field=models.DateTimeField(verbose_name=datetime.datetime(2024, 5, 20, 5, 7, 0, 627065)),
        ),
    ]
